### ISSUE TITLE
Il manque le bouton pour les commentaires :)

### ISSUE THREAD

**Issue by armSeb** [maximegorjux/leparisien#2]
Bonjour,

Merci pour votre script qui fonctionne super bien. Néanmoins un petit bug, le bouton des commentaires n'apparaît plus. Il semblerait qu'il est supprimé par le code qui floute l'article, du coup je pense qu'il faut une petite manip soit pour changer la classe du bouton le temps que le javascript de la page ait fini de faire son job (pour l'empêcher d'être supprimé), ou bien avoir un code qui remet un bouton permettant de lire les commentaires de l'article.

Seb.

**Comment by armSeb** [comment]
J'ai juste ajouté une ligne, c'est cra-cra mais ça marche : 

`    $(".width_full.flex").append('<button class="primary-button comment ui_bold">Commentaires</button>');`

Du coup c'est ce bouton qui est supprimé, et celui pour les commentaires reste en place :)

**Comment by maximegorjux** [comment]
Super, j'essaierai de trouver une meilleure manière de faire, sinon je publierai cette modif, merci :)

**Comment by maximegorjux** [comment]
J'ai pas l'impression que le problème vienne de mon script, dans tous les cas ta proposition fonctionne parfaitement, j'ai juste changé 2-3 trucs pour éviter d'un bouton s'affiche quelques secondes.

Encore merci, je n'avais jamais fait attention au bouton commentaire :)

**Comment by armSeb** [comment]
Non, le problème ne vient pas du script.

C'est le script abonnement qui le supprime lorsqu'il floute l'article pour empêcher la lecture des commentaires. Le code que j'ai proposé permet juste de lui faire supprimer un bouton factice et donc de conserver l'original. Je suppose qu'un changement de la classe du "vrai" bouton aurait le même effet :)

**Comment by maximegorjux** [comment]
Normalement c'est corrigé, je me suis basé sur ta proposition, et j'ai rajouté cette ligne :
`$(".width_full.flex").append('<div class="primary-button comment ui_bold" style="display: none;"></div>');`

**Comment by armSeb** [comment]
Je confirme que c'est corrigé, merci :)
